spring.application.name=agendei-backend

# Conexão com o Postgres (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/agendei_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate) - Cria tabelas sozinho
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true