spring.application.name=agendei-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/agendei_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Segredo para assinar o Token JWT (Em produ\u00E7\u00E3o, isso seria uma vari\u00E1vel de ambiente!)
api.security.token.secret=meu-segredo-super-secreto-agendei